version: "3"

volumes:
  psgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOL_DIR}/psgdata
  gsvdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOL_DIR}/gsvdata


services:
  database:
    ports:
      - "127.0.0.1:${DB_PORT_EXPOSE}:5432"
  
  geoserver:
    ports:
      - "127.0.0.1:${GEOSERVER_PORT}:8080"
  
  webserver:
    ports:
      - "127.0.0.1:${WS_PORT}:7500"