version: "3"

volumes:
  psgdata:
  gsvdata:


services:
  importer:
    logging:
      options:
        labels: "debug"

  database:
    ports:
      - "${DB_PORT_EXPOSE}:5432"
  
  geoserver:
    ports:
      - "${GEOSERVER_PORT}:8080"
  
  webserver:
    ports:
      - "${WS_PORT}:7500"
    logging:
      options:
        labels: "debug"