"""empty message

Revision ID: 3a5c328de87f
Revises: 3baf44718c07
Create Date: 2022-12-23 09:24:48.557069

"""
from alembic import op
import sqlalchemy as sa
import importer


# revision identifiers, used by Alembic.
revision = '3a5c328de87f'
down_revision = '3baf44718c07'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('datatype_id', sa.String(length=64), nullable=False),
        sa.Column('style', sa.String(length=64), nullable=True),
        sa.Column('delete_after_days', sa.Integer(), nullable=True),
        sa.Column('delete_after_count', sa.Integer(), nullable=True),
        sa.Column('format', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id')
    # ### end Alembic commands ###
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layer_settings')
    # ### end Alembic commands ###