"""

Revision ID: 3baf44718c07
Revises: b6d4a63a305d
Create Date: 2022-08-24 12:19:40.075012

"""
from alembic import op
import sqlalchemy as sa
import importer


# revision identifiers, used by Alembic.
revision = '3baf44718c07'
down_revision = 'b6d4a63a305d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geoserver_resource', sa.Column('mosaic', sa.Boolean(), server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geoserver_resource', 'mosaic')
    # ### end Alembic commands ###
