"""

Revision ID: b6d4a63a305d
Revises: ac2b867d2b7c
Create Date: 2022-01-04 19:22:50.225849

"""
from alembic import op
import sqlalchemy as sa
import importer

# revision identifiers, used by Alembic.
revision = 'b6d4a63a305d'
down_revision = 'ac2b867d2b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geoserver_resource', sa.Column('timestamps', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geoserver_resource', 'timestamps')
    # ### end Alembic commands ###
